### ISSUE TITLE
Genexis system-backup.sh hash

### ISSUE THREAD

**Issue by markozajc** [dg1yiq/USRP_Tetra_Bridge#1]
Greetings!
I know this is the wrong place for such inquiries, but I was unable to contact you elsewhere. I've found out you figured out where and how hashing of Genexis routers' backups is done [here](http://support.buerger-fuer-glasfaser.de/showthread.php?tid=197&pid=1757#pid1757), but you didn't provide any further information due to copyright problems. I happen to have a Genexis router myself, but I'm unable to access the filesystem, and would greatly appreciate if you shared the hashing code you found with me. If you want to do it in private, you can send me a mail to marko@zajc.eu.org
Best regards
Marko Zajc

**Comment by dg1yiq** [comment]
Hello Marko,

yes I can not publish any code here because of copyright issues... this code is property of genesis.

Maybe I can help you to gain the necessary information by yourself.

greetings
Marco
