### ISSUE TITLE
Cant't send AT command to MTM800E

### ISSUE THREAD

**Issue by Betty1909** [dg1yiq/USRP_Tetra_Bridge#2]
I have enable SDS remote control on my MTM800E, but still can't activaten call controll on PEI.
I have try RPI gpio UART and USB TTL, they not work.
Is there any good way to solve it?
Thanks! Sorry for my bad English.

**Comment by dg1yiq** [comment]
Hello,

did you check following settings in codeplug:

-> Data Services -> PEI Parameters

Special attention to the serial settings like "flow control" to "no flow control"...

greetings
Marco

**Comment by Betty1909** [comment]
Thanks!
I have check parity bit on PARITY_NONE
and ETSI AT SDS check
And not work. :(

**Comment by Betty1909** [comment]
Today I change a new MTM800E and using FTDI FT232RL 3.3V and not work again. :(
Need help please!

**Comment by dg1yiq** [comment]
Hello,

send me your Codeplug via mail... I will check it... also how did you connected RS232 to your radio?
Did you try to communicate diretly via RS232 with the radio (example with minicom?) - will it response to a simple "AT" command with a OK?

greetings
Marco

PS: My Mail Address marco.reinke(at)me.com

**Comment by Betty1909** [comment]
Dear Marco
When I trying 3.3v CP2102 TTL to radio
It suddenly work, lol
Thanks for your help, and nice code! :)
BM6HLR, 73
